general:
  telemetry:
    tracing:
      file_trace:
        _type: file
        output_path: ./dabstep_agent/dabstep_traces.jsonl
        project: dabstep-agent

function_groups:
  python_executor:
    _type: python_executor
    timeout: 120
    sys_paths:
      - dabstep_agent
    workspace_dir: dabstep_agent/workspace

llms:
  agent_llm:
    _type: openai
    api_key: $API_KEY
    model_name: claude-haiku-4-5
    base_url: https://api.anthropic.com/v1/

workflow:
  _type: tool_calling_agent
  llm_name: agent_llm
  verbose: true
  tool_names: [python_executor]
  max_history: 50
  max_iterations: 20
  handle_tool_errors: true
  additional_instructions: |
    You are a data science expert. The task is tabular data QA.

    Use execute_python_code tool to write code and answer the question.
    Don't over explore. 
    When the results are ready, stop calling tools and return it as final output immediately.

    Output Format:
    {
        "agent_answer": your_answer based on provided GUIDELINES
    }
    Don't write anything else!
