import json
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime
from typing import List, Tuple
from qa_agent import QAAgent, load_question
from simple_qa_agent import SimpleQAAgent
from extract_structure_example import (
    create_structure_extraction_agent,
    extract_all_structures,
    format_structures_for_prompt
)
from dotenv import load_dotenv

load_dotenv()


def save_generated_code(task_id: str, code_snippets: List[str], workspace_dir: str = "workspace"):
    """Save generated code snippets to a Python file in the workspace directory.

    Args:
        task_id: The task ID (used for filename)
        code_snippets: List of code snippets generated by the agent
        workspace_dir: Directory to save code files (default: workspace)
    """
    os.makedirs(workspace_dir, exist_ok=True)
    filepath = os.path.join(workspace_dir, f"task{task_id}.py")

    with open(filepath, 'w') as f:
        f.write(f"# Generated code for task {task_id}\n")
        f.write(f"# Total code snippets: {len(code_snippets)}\n\n")
        for i, code in enumerate(code_snippets, 1):
            f.write(f"# --- Snippet {i} ---\n")
            f.write(code)
            f.write("\n\n")

    print(f"Generated code saved to: {filepath}")


def extract_agent_answer(answer: str) -> str:
    """Extract the agent_answer value from a response (may be embedded in text)."""
    import re
    if answer is None:
        return ""
    answer = str(answer).strip()
    # Try to extract agent_answer from JSON (may be embedded in text)
    json_match = re.search(r'\{\s*"agent_answer"\s*:\s*"([^"]*)"\s*\}', answer)
    if json_match:
        return json_match.group(1).strip()
    # Try direct JSON parse
    try:
        parsed = json.loads(answer)
        if isinstance(parsed, dict) and 'agent_answer' in parsed:
            return str(parsed['agent_answer']).strip()
    except (json.JSONDecodeError, TypeError):
        pass
    return answer


def normalize_answer_for_comparison(answer: str) -> str:
    """Normalize an answer for comparison. If it's a comma-separated list of numbers, sort them."""
    answer = extract_agent_answer(answer)
    # Check if it's a comma-separated list of numbers
    try:
        parts = [p.strip() for p in answer.split(',')]
        # Try to parse all parts as numbers
        numbers = [float(p) for p in parts if p]
        # If we got here, it's a list of numbers - sort them
        # Use int if all are integers, otherwise keep as float
        if all(n == int(n) for n in numbers):
            numbers = [int(n) for n in numbers]
        numbers.sort()
        return ', '.join(str(n) for n in numbers)
    except (ValueError, AttributeError):
        # Not a list of numbers, return as-is
        return answer


def compare_answers(agent_answer: str, ground_truth: str) -> bool:
    """Compare two answers, sorting if they are comma-separated number lists."""
    norm_agent = normalize_answer_for_comparison(agent_answer)
    norm_gt = normalize_answer_for_comparison(ground_truth)
    return norm_agent == norm_gt


def save_agent_answer(task_id: str, answer: str, output_file: str = "agent_answers.jsonl"):
    """Append extracted agent answer to a JSONL file."""
    extracted = extract_agent_answer(answer)
    record = {"task_id": task_id, "agent_answer": extracted}
    with open(output_file, 'a') as f:
        f.write(json.dumps(record) + '\n')


# Global variable to hold pre-extracted file structures
_FILE_STRUCTURES = None


def extract_file_structures_once(data_dir: str = "data/context") -> str:
    """Extract file structures once and cache them."""
    global _FILE_STRUCTURES
    if _FILE_STRUCTURES is None:
        print("Pre-extracting file structures...")
        structure_agent = create_structure_extraction_agent()
        structures = extract_all_structures(structure_agent, data_dir)
        _FILE_STRUCTURES = format_structures_for_prompt(structures)
        print("File structures extracted and cached.\n")
    return _FILE_STRUCTURES


def _solve_task_worker(task_id: int, file_structures: str = None, tasks_file: str = "data/tasks_dev.json") -> dict:
    """Internal worker for batch/parallel execution. Returns structured result dict with error handling."""
    try:
        # Create QAAgent instance
        agent = QAAgent(
            data_dir="data/context",
            tasks_file=tasks_file,
            file_structures=file_structures,
            default_search_terms=['null'],
            verbose=True
        )

        question = agent.get_question(task_id)
        answer = agent.solve(task_id)

        return {
            "task_id": question.get("task_id", task_id),
            "question": question["question"],
            "expected_answer": question.get("answer", "N/A"),
            "agent_answer": answer,
            "status": "success"
        }
    except Exception as e:
        return {
            "task_id": task_id,
            "question": "N/A",
            "expected_answer": "N/A",
            "agent_answer": None,
            "status": "error",
            "error": str(e)
        }


def solve_all_tasks_parallel(max_workers: int = 4, output_file: str = None, tasks_file: str = "data/tasks_dev.json"):
    """
    Solve all dabstep tasks in parallel and write results to a file.

    Args:
        max_workers: Number of parallel workers
        output_file: Output file path (default: results_<timestamp>.json)
    """
    # Pre-extract file structures once before parallel execution
    file_structures = extract_file_structures_once()

    # Load all questions to get the count
    with open(tasks_file, 'r') as f:
        questions = json.load(f)

    num_tasks = len(questions)
    print(f"Found {num_tasks} tasks to solve")

    # Generate output filename if not provided
    if output_file is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = f"results_{timestamp}.json"

    results = []
    completed = 0

    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        # Submit all tasks with pre-extracted structures
        future_to_task = {
            executor.submit(_solve_task_worker, task_id, file_structures, tasks_file): task_id
            for task_id in range(num_tasks)
        }

        # Collect results as they complete
        for future in as_completed(future_to_task):
            task_id = future_to_task[future]
            try:
                result = future.result()
                results.append(result)
                completed += 1
                print(f"\n[Progress: {completed}/{num_tasks}] Task {task_id} completed - Status: {result['status']}")
            except Exception as e:
                results.append({
                    "task_id": task_id,
                    "status": "error",
                    "error": str(e)
                })
                completed += 1
                print(f"\n[Progress: {completed}/{num_tasks}] Task {task_id} failed with exception: {e}")

    # Sort results by task_id for consistent ordering
    results.sort(key=lambda x: x.get("task_id", 0) if isinstance(x.get("task_id"), int) else 0)

    # Calculate summary statistics
    successful = sum(1 for r in results if r["status"] == "success")
    failed = sum(1 for r in results if r["status"] == "error")

    output_data = {
        "summary": {
            "total_tasks": num_tasks,
            "successful": successful,
            "failed": failed,
            "timestamp": datetime.now().isoformat()
        },
        "results": results
    }

    # Write results to file
    with open(output_file, 'w') as f:
        json.dump(output_data, f, indent=2)

    print(f"\n{'=' * 70}")
    print(f"All tasks completed!")
    print(f"Total: {num_tasks}, Successful: {successful}, Failed: {failed}")
    print(f"Results written to: {output_file}")
    print(f"{'=' * 70}")

    return output_data


def solve_task(task_id: int, tasks_file: str = "data/tasks_dev.json") -> Tuple[str, List[str]]:
    """Solve a single task using SimpleQAAgent. CLI entry point.

    Returns:
        Tuple of (answer, list of generated code snippets)
    """
    file_structures = extract_file_structures_once()
    agent = SimpleQAAgent(
        data_dir="data/context",
        tasks_file=tasks_file,
        file_structures=file_structures,
        max_iterations=100,
        verbose=True
    )
    return agent.solve(task_id)


def learn_single(task_id: int, gt_answer: str, tasks_file: str = "data/tasks_dev.json"):
    """Learn from a single task using QAAgent with ground truth answer."""
    # Pre-extract file structures
    file_structures = extract_file_structures_once()

    # Create and use QAAgent
    agent = QAAgent(
        data_dir="data/context",
        tasks_file=tasks_file,
        file_structures=file_structures,
        default_search_terms=['null'],
        verbose=False
    )

    answer, rule = agent.learn(task_id, gt_answer)

    # Print extracted rule separately for easy access
    if rule:
        print("\n" + "=" * 70)
        print("EXTRACTED RULE/INSIGHT:")
        print("=" * 70)
        print(rule)
        print("=" * 70 + "\n")

    return answer, rule


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="DABStep Task Solver")
    parser.add_argument("--parallel", action="store_true", help="Run all tasks in parallel")
    parser.add_argument("--workers", type=int, default=4, help="Number of parallel workers (default: 4)")
    parser.add_argument("--task", type=int, default=None, help="Solve a single task by row index")
    parser.add_argument("--task-id", type=str, default=None, help="Solve a single task by task_id field")
    parser.add_argument("--output", type=str, default="agent_answers.jsonl", help="Output JSONL file for agent answers")
    parser.add_argument("--learn", action="store_true", help="Learn mode: find code that produces ground truth answer")
    parser.add_argument("--gt-answer", type=str, default=None, help="Ground truth answer for learn mode")
    parser.add_argument("--input", type=str, default="data/tasks_dev.json", help="Path to input tasks JSON file (default: data/tasks_dev.json)")

    args = parser.parse_args()

    # Helper function to find row index by task_id
    def find_task_index_by_id(task_id: str, tasks_file: str) -> int:
        with open(tasks_file, 'r') as f:
            questions = json.load(f)
        for idx, q in enumerate(questions):
            if q.get("task_id") == task_id:
                return idx
        raise ValueError(f"Task with task_id '{task_id}' not found in {tasks_file}")

    # Resolve task index from --task-id if provided
    task_index = args.task
    if args.task_id is not None:
        task_index = find_task_index_by_id(args.task_id, args.input)
        print(f"Found task_id '{args.task_id}' at row index {task_index}")

    if args.parallel:
        solve_all_tasks_parallel(max_workers=args.workers, output_file=args.output, tasks_file=args.input)
    elif args.learn:
        if task_index is None:
            print("Error: --learn requires --task or --task-id to specify the task")
            exit(1)
        if args.gt_answer is None:
            # Try to get gt_answer from the task's answer field
            with open(args.input, 'r') as f:
                questions = json.load(f)
            if task_index < len(questions) and "answer" in questions[task_index]:
                gt_answer = questions[task_index]["answer"]
                print(f"Using answer from task file: {gt_answer}")
            else:
                print("Error: --learn requires --gt-answer or task must have 'answer' field")
                exit(1)
        else:
            gt_answer = args.gt_answer
        learn_single(task_index, gt_answer, tasks_file=args.input)
    elif task_index is not None:
        # Load task info to display ground truth
        with open(args.input, 'r') as f:
            questions = json.load(f)
        task_info = questions[task_index]

        print(f"\n{'=' * 70}")
        print(f"Task Index: {task_index}")
        print(f"Task ID: {task_info.get('task_id', 'N/A')}")
        print(f"Level: {task_info.get('level', 'N/A')}")
        print(f"Question: {task_info.get('question', 'N/A')}")
        print(f"Ground Truth Answer: {task_info.get('answer', 'N/A')}")
        print(f"Guidelines: {task_info.get('guidelines', 'N/A')}")
        print(f"{'=' * 70}\n")

        answer, code_snippets = solve_task(task_index, tasks_file=args.input)

        # Save generated code to workspace
        save_generated_code(task_info.get('task_id', str(task_index)), code_snippets)

        print(f"\n{'=' * 70}")
        print(f"RESULT COMPARISON")
        print(f"{'=' * 70}")
        print(f"Agent Answer:       {answer}")
        print(f"Ground Truth Answer: {task_info.get('answer', 'N/A')}")
        print(f"Match: {compare_answers(answer, task_info.get('answer', ''))}")
        print(f"{'=' * 70}\n")
        save_agent_answer(task_info.get('task_id', ''), answer, args.output)
    else:
        # Default: solve task 0
        with open(args.input, 'r') as f:
            questions = json.load(f)
        task_info = questions[0]

        print(f"\n{'=' * 70}")
        print(f"Task Index: 0")
        print(f"Task ID: {task_info.get('task_id', 'N/A')}")
        print(f"Level: {task_info.get('level', 'N/A')}")
        print(f"Question: {task_info.get('question', 'N/A')}")
        print(f"Ground Truth Answer: {task_info.get('answer', 'N/A')}")
        print(f"Guidelines: {task_info.get('guidelines', 'N/A')}")
        print(f"{'=' * 70}\n")

        answer, code_snippets = solve_task(0, tasks_file=args.input)

        # Save generated code to workspace
        save_generated_code(task_info.get('task_id', '0'), code_snippets)

        print(f"\n{'=' * 70}")
        print(f"RESULT COMPARISON")
        print(f"{'=' * 70}")
        print(f"Agent Answer:       {answer}")
        print(f"Ground Truth Answer: {task_info.get('answer', 'N/A')}")
        print(f"Match: {compare_answers(answer, task_info.get('answer', ''))}")
        print(f"{'=' * 70}\n")
        save_agent_answer(task_info.get('task_id', ''), answer, args.output)
